### PR TITLE
chore(fastify): upgrade fastify to 4.x

### PR DESCRIPTION
**Pull request by gjuchault**
Hello!

Fastify just released their version 4, so here's the update in this package.

I also upgraded `engines.node` to v14 (in Github Actions as well) as I think fastify started to use [Optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), introduced in node 14.

3 tests are failing with wrapRoutes, so I'm investigating them at the moment

### CODE REVIEW

**Comment by gjuchault** [comment]
The issue with tests seems to come from the fact that `onRoute` is only called with the `HEAD` method, and not with the `GET` one. What's weird is this happens even when giving `exposeHeadRoutes: false` to fastify' settings

**Comment by HW13** [comment]
Thanks for taking this on @gjuchault!

It looks like the issues with the tests can be resolved by adding `await` to the `fastify.register` and `fastify.get` calls in both the failing tests ([here](https://github.com/autotelic/fastify-opentelemetry/blob/main/test/index.test.js#L200-L215) and [here](https://github.com/autotelic/fastify-opentelemetry/blob/main/test/index.test.js#L242-L248)).

**Comment by HW13** [comment]
While I can't seem to find an actual list of breaking changes, this seems to be one. [This](https://medium.com/@fastifyjs/fastify-v4-ga-59f2103b5f0e) post regarding the v4 release mentions route registration becoming synchronous - looks like only `fastify.register` needs the `await` (but you've already implemented that way 👍)

**Review by HW13 — APPROVED** [review]
LGTM, thanks @gjuchault! 😎 👍

**Pull request merged**
